name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install OpenCL dependencies
        run: |
          sudo apt update
          sudo apt install -y ocl-icd-opencl-dev opencl-headers clinfo

      - name: Check OpenCL installation
        run: clinfo

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
